version: '3.8'

services:
  db:
    image: postimage:latest  # Use the already built database image
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432

  web:
    image: django-app:latest  # Use the already built Django app image
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Expose Django app on host port 8000
    depends_on:
      - db
